### ISSUE TITLE
Reproduce results from CAMUS leaderboard

### ISSUE THREAD

**Issue by GEJansen** [HangJung97/ASCENT#67]
Hey, thanks for sharing this repository. I was wondering: how do I reproduce your results from the leaderboard of [CAMUS](https://www.creatis.insa-lyon.fr/Challenge/camus/results.html)?

Which commands do I have to run? Is it simply:
```
ascent_train experiment=camus_2d logger=tensorboard
```
as outlined in the readme file?

**EDIT**: some afterthoughts

Do I leave the image dimensions, and pixel aspect ratios as is, when converting the CAMUS data to the desired format?

Also, is this implementation any different from the original nnUnet?  As in, can I expect different results if I train on the same data with the original nnUnet implementation?

**Comment by HangJung97** [comment]
Hi, thank you for your interest! I will try to answer all your questions but perhaps not in order. 😁 ASCENT is similar to nnUNet but not identical, e.g.. Monai is used for all the data loading stuffs, Lightning instead of pure PyTorch, etc. The results obtained with ASCENT should be comparable to nnUNet (I didn't notice much difference between the segmentations produced by ASCENT and nnUNet for CAMUS dataset).

To reproduce my results from CAMUS leaderboard, it's pretty simple. 

1. Follow the [camus conversion script](https://github.com/HangJung97/ASCENT/blob/main/ascent/dataset_conversion/camus.py) to convert the training dataset and test dataset to the correct format (I've updated the readme). You don't have to alter any image voxel spacing. 
2. Afterwards, run the preprocessing command `ascent_preprocess_and_plan dataset=CAMUS_challenge pl2d=False pl3d=False` (Set the 2D and 3D planners to false to avoid the regeneration of config files). 
3. To train a 2D U-Net on CAMUS: `ascent_train experiment=camus_challenge_2d logger=tensorboard datamodule.test_splits=False`. Usually I split my dataset into train/val/test but since it was a challenge, I disabled the test split to train on the maximum number of data.
4. Once the model is trained, use `ascent_predict` to run inference on the test data.
5. Finally, convert back the predicted segmentations back to the submission format as indicated [here](https://github.com/HangJung97/ASCENT/blob/main/ascent/dataset_conversion/camus.py).

Hope my explanations are clear.

**Comment by GEJansen** [comment]
Awesome, I think you answered all my questions 😁

I had overfitting problems when training the original 2D nnUnet on the CAMUS dataset, and I did not achieve the same results as you did. Did you experience any such problems? Perhaps I did something wrong with the data conversion. 

Anyways, I might give this a try, thank you!

**Comment by HangJung97** [comment]
There should be no overfitting when training with the original 2D nnUNet repository, at least from all my experiments. You can reuse the converted data using my conversion script to train with the nnUNet again, as they are the same and share the same dataset.json. You can keep me updated. 😄
